// automatically generated by the FlatBuffers compiler, do not modify

package Sample

const (
	ColorRed = 0
	ColorGreen = 1
	ColorBlue = 2
)

var EnumNamesColor = map[int]string{
	ColorRed:"Red",
	ColorGreen:"Green",
	ColorBlue:"Blue",
}

