// automatically generated by the FlatBuffers compiler, do not modify

package Sample

const (
	EquipmentNONE = 0
	EquipmentWeapon = 1
)

var EnumNamesEquipment = map[int]string{
	EquipmentNONE:"NONE",
	EquipmentWeapon:"Weapon",
}

